sshconfig: ENC[AES256_GCM,data:IldL1Ek6n2EEMSwkegHnh+1xQmSrUpiOGGr1WIBrG+R3hoIx8WG3hrCSiQqvzktHftMxfXBcECPcsy/IBuUU4DoYbUWkHdcZIn+ex34846W/Xb7s65viCGKjc/ThY3MBbiZyAA8NscP50haqEkXoMauCzKDxJVJcdMveaKSux368+thjKVRN/uR/puj0LFG65mZwSrhJE+dwnIS29E3Odxc2f8IZVm9FgEHkUmPNb4SMY6m5YS7OaGTqf3smtebRhQUrPwJES3vjFgxTwFGnL2VuvShOYZjQlaMXLYIZA1Tmn3wqNF9Sw8eNg2x6HhVKA0N1HL8r6fmQyPFcpd+yCsWfKUrbudkWpTEMNymfkq8SuGooSJlR3kLsY0X55LR8SWRfc9Mg6lazuJq337c7lGEazWnawoANgTIj4w==,iv:5EHpPaQTexcjlUacFhhQ4+/R3TC9cCMIFH5N/v6sdFQ=,tag:16Ocv2h6KoPiDeYIX5GPAg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIpOQirGxMfUl3F8KQxjzDZg0POSIpeNk5ayZQvugQOm li.aldric@gmail.com
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEZBSExQQSByOWI2
            ajZXb2FLd3V6elVYR1JZeUZLWmVVanJ3MytJTGw5L2JPMWZkUFdvCmVNVi9iL3V1
            YlVWeXlvRXFYMUlZNDB1aUk1OUhaenZpSk9INmVMYzV0eTAKLS0tIFpYVXl6YzZM
            aVBrVDh0eHFrVFp0ZmIrYTNzQVBCSUU0aHNobDRwVEN6VlUK5CDT1/88LHVU3+og
            XLOwU/D00DFqUf6n/Od5NquhFrJmT8ZzTuylTn2mHngHwztJ4ssl4E8vY1ARkC7I
            qRDa7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHg3soSwDR48yhLBm6KvBQliWcNbaPgd1D3QEk+Nu8EN li.aldric@gmail.com#nix-wsl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHVFKzRpUSAveG9K
            b1pvNldpRmtNUTYwd0NVeUxiU0IyUjdadzBVZlV1Y0U3S1FZcVRNCmVEelBDVjZ5
            bW9iS3ZIZVRVZ2tnWEtudEU5dnZ0Y3BJTEY5eHpEQVlDRlkKLS0tIHgwV3lHYUZX
            UmlIdjJSWit2YU1YNXBFdHlpdmVPKzJ4eUg4SFd0bzkwZmMKhG41blhEuHYUPLHQ
            aAZirqSAQkddMd8T7o/3Oc7C1YChwH6QvxRy+FJmug2XhgaaPJ/FczbrWjSbSVAz
            /Cw43A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPlXUXQeII1CLwhf83/Y8fMLQ0qAai7MrthZrhElsRhF li.aldric@gmail.com#debian
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGM3ME1TZyBZRFVx
            cUZBTEIvckd1Y1k3ZW1OWlpydHFob29XL0FQQ1JWRDI2WVFqTUFVClFReHhxcnQz
            Wk5TTzlESVN6bWc0L3RiNkRDUnlnK1dRdWNBdkszcFF4OE0KLS0tIE9ybWlMK2dB
            U2hobkZ1NlFCVTliUzluTDFZK0dvd0NFcVZOWXpUZk9xbVkKdhgv5CgpTJBPnI/Z
            iSDLLXSNdsQH+ORD9vrvij3Md2OSC1yVZt/PmXB5sTUzhK6PRgx7GKDCWt+KGcAk
            +fXjww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T10:55:05Z"
    mac: ENC[AES256_GCM,data:2kzdxY2keK2Y8YTxfWIFYpZTs1Ss3ewT0Q3PBUDwaHZWPpyEMkLehkpMq0qR0T7KMIg2zNhor3j907BcwMUCFqbL8gVTd6ktLsY7VVIFju1QkBuEKDCPz7Nj23GC8IJAeJLIGgWcajgDTJAQ/B1K4hzp106F2MhaBWuwahb2bE0=,iv:EaakdJYcZ+emmO5OrMYI7eSynva3s49ePUYekOwlQ3I=,tag:zuJgFKSebFDJd/GfRD6DoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
