sshconfig: ENC[AES256_GCM,data:IldL1Ek6n2EEMSwkegHnh+1xQmSrUpiOGGr1WIBrG+R3hoIx8WG3hrCSiQqvzktHftMxfXBcECPcsy/IBuUU4DoYbUWkHdcZIn+ex34846W/Xb7s65viCGKjc/ThY3MBbiZyAA8NscP50haqEkXoMauCzKDxJVJcdMveaKSux368+thjKVRN/uR/puj0LFG65mZwSrhJE+dwnIS29E3Odxc2f8IZVm9FgEHkUmPNb4SMY6m5YS7OaGTqf3smtebRhQUrPwJES3vjFgxTwFGnL2VuvShOYZjQlaMXLYIZA1Tmn3wqNF9Sw8eNg2x6HhVKA0N1HL8r6fmQyPFcpd+yCsWfKUrbudkWpTEMNymfkq8SuGooSJlR3kLsY0X55LR8SWRfc9Mg6lazuJq337c7lGEazWnawoANgTIj4w==,iv:5EHpPaQTexcjlUacFhhQ4+/R3TC9cCMIFH5N/v6sdFQ=,tag:16Ocv2h6KoPiDeYIX5GPAg==,type:str]
sops:
    age:
        - recipient: age1uyg73jl64msxu5x7rmed0japawg22z7qqdye5xj9a7tx2vaqpdnqe3jdmx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU3lYS3M5a0tDNXVFQ080
            ajNMNVhQYkovdk1NTDJQZlJwQURUWHRNOEM0CmVNUjY2dFJ0eEhnZ3FKY3RPVG16
            eHBuR2tBcGZWMGtCRVlZLy9zOU84ZzgKLS0tIEdVZHVkL21GSFg3QU50Y3JuaHpp
            RHJUMC9WUnFZb09YcnZhbmQ1OHNFVkUKcmjyzOeLu9E2hSSTKPDhRR2W4NKDFO02
            k0hYkEVMsAjVhHzvSLjDJkiBom6VurGxR+OZyGoJRnYCYmi4SjlfCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8n4p9de897fepp6cxk0jtz7jynkmexgyhgyjtwmsvkuu09mk56qfyzsr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNldyYStybDRnK0VxZ0tE
            enZuYk9naTV6UFR5NHNGcEZiZjR2SWJPS0g4Ck8rVHFEWEVXcjgxdGN3WWZQQmNq
            OUg5OFNkVy9CV1BKQmZzQlpVWW5ZQlUKLS0tIHArc21mYjgvVVBnRVd4NWFJS1JH
            MlZOeDNxdGVxWkFsZ3J2WFJCdWNLQ1UKHZG688CCA9mB50ifJgieaFEL8mPXhQW/
            O4aYxkYW6qXLp/eYmNdwXEpbKRlzAWWEYoXIEN7cagLZ/UzI54LsPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1955ta5htsxpmpwa2j64gznev5hh4tnz8v5asnz6q2mjlxjkzt4hs6sgyyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRC93ZVkweitHeFNSL2hO
            UzhvZ2hQaEcycFQvcTFEMktwcno3K0owZXlRCkN3cyt4MjVVSlYyMXRycFpDdTRh
            TzYwYzZjQVA5eWJva1lTb0JuNzBvSkEKLS0tIEZVczlmNkZITWU0dUdKT2tmdkxC
            Uy9MQ21yYVBacTAvMXVlbm5BMTNUNE0Kl9G+XFr6tsqIVZmlpDHsXK0zGaqsnTou
            WyLJj4zoMCKLmc9aJLKdVg9INJCuoIPPWoPsjwSnc7SedUzJBxBaUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T10:55:05Z"
    mac: ENC[AES256_GCM,data:2kzdxY2keK2Y8YTxfWIFYpZTs1Ss3ewT0Q3PBUDwaHZWPpyEMkLehkpMq0qR0T7KMIg2zNhor3j907BcwMUCFqbL8gVTd6ktLsY7VVIFju1QkBuEKDCPz7Nj23GC8IJAeJLIGgWcajgDTJAQ/B1K4hzp106F2MhaBWuwahb2bE0=,iv:EaakdJYcZ+emmO5OrMYI7eSynva3s49ePUYekOwlQ3I=,tag:zuJgFKSebFDJd/GfRD6DoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
